### ISSUE TITLE
[BUG?] pages not loading (php)

### ISSUE THREAD

**Issue by atomGit** [pageer/lnblog#55]
hello again Peter

manjaro linux
lnblog 2.3.2
apache 2.4.57
php-apache 8.2.11

several pages are not loading - for ex. i created a new blog and clicked the link in the admin UI to go to it and all was well, and then at some point it wouldn't load anymore

thought this may be a permissions problem, so i ran the tool to fix permissions but that results in an error as well

i'm not well versed in any of this so if you need more info, let me know

i've removed a few redundant lines in the log...

<details>
<summary>httpd error_log</summary>

```
[Mon Oct 09 07:56:21.462799 2023] [mpm_prefork:notice] [pid 3589] AH00163: Apache/2.4.57 (Unix) PHP/8.2.11 configured -- resuming normal operations
[Mon Oct 09 07:56:21.462854 2023] [core:notice] [pid 3589] AH00094: Command line: '/usr/bin/httpd -D FOREGROUND'
[Mon Oct 09 07:57:32.801242 2023] [php:warn] [pid 3593] [client 127.0.0.1:36928] PHP Warning:  Constant FS_PLUGIN already defined in /srv/http/lnblog/lib/AdminPages.php on line 917, referer: http://localhost:8000/lnblog/?action=fssetup
[Mon Oct 09 07:57:32.801440 2023] [php:warn] [pid 3593] [client 127.0.0.1:36928] PHP Warning:  Constant FS_PLUGIN already defined in /srv/http/userdata/fsconfig.php on line 2, referer: http://localhost:8000/lnblog/?action=fssetup
[Mon Oct 09 07:57:32.801446 2023] [php:warn] [pid 3593] [client 127.0.0.1:36928] PHP Warning:  Constant FS_DEFAULT_MODE already defined in /srv/http/userdata/fsconfig.php on line 3, referer: http://localhost:8000/lnblog/?action=fssetup
[Mon Oct 09 07:57:32.801450 2023] [php:warn] [pid 3593] [client 127.0.0.1:36928] PHP Warning:  Constant FS_SCRIPT_MODE already defined in /srv/http/userdata/fsconfig.php on line 4, referer: http://localhost:8000/lnblog/?action=fssetup
[Mon Oct 09 07:57:32.801453 2023] [php:warn] [pid 3593] [client 127.0.0.1:36928] PHP Warning:  Constant FS_DIRECTORY_MODE already defined in /srv/http/userdata/fsconfig.php on line 5, referer: http://localhost:8000/lnblog/?action=fssetup
[Mon Oct 09 08:02:24.747850 2023] [php:warn] [pid 3592] [client 127.0.0.1:58560] PHP Warning:  Undefined variable $PWD in /srv/http/lnblog/themes/default/templates/login_create_tpl.php on line 73, referer: http://localhost:8000/lnblog/index.php?action=index
[Mon Oct 09 08:02:48.608414 2023] [php:warn] [pid 3594] [client 127.0.0.1:43772] PHP Warning:  Undefined variable $PWD in /srv/http/lnblog/themes/default/templates/login_create_tpl.php on line 73, referer: http://localhost:8000/lnblog/
[Mon Oct 09 08:19:37.527991 2023] [php:error] [pid 3590] [client 127.0.0.1:53892] PHP Fatal error:  Uncaught TypeError: readdir(): Argument #1 ($dir_handle) must be of type resource or null, bool given in /srv/http/lnblog/lib/FS.php:332\nStack trace:\n#0 /srv/http/lnblog/lib/FS.php(332): readdir()\n#1 /srv/http/lnblog/lib/Blog.php(1120): FS->scan_directory()\n#2 /srv/http/lnblog/lib/Blog.php(1125): Blog->fixDirectoryPermissions()\n#3 /srv/http/lnblog/lib/AdminPages.php(216): Blog->fixDirectoryPermissions()\n#4 /srv/http/lnblog/lib/AdminPages.php(53): AdminPages->index()\n#5 /srv/http/lnblog/lib/BasePages.php(137): AdminPages->defaultAction()\n#6 /srv/http/lnblog/lib/BasePages.php(66): BasePages->handleRequestRouting()\n#7 /srv/http/lnblog/index.php(5): BasePages->routeRequest()\n#8 {main}\n  thrown in /srv/http/lnblog/lib/FS.php on line 332, referer: http://localhost:8000/lnblog/
[Mon Oct 09 08:31:02.950939 2023] [php:warn] [pid 3624] [client 127.0.0.1:60918] PHP Warning:  opendir(/srv/http/12bytes/entries): Failed to open directory: Permission denied in /srv/http/lnblog/lib/FS.php on line 330, referer: http://localhost:8000/lnblog/
[Mon Oct 09 08:31:02.950996 2023] [php:error] [pid 3624] [client 127.0.0.1:60918] PHP Fatal error:  Uncaught TypeError: readdir(): Argument #1 ($dir_handle) must be of type resource or null, bool given in /srv/http/lnblog/lib/FS.php:332\nStack trace:\n#0 /srv/http/lnblog/lib/FS.php(332): readdir()\n#1 /srv/http/lnblog/lib/Storage/EntryRepository.php(167): FS->scan_directory()\n#2 /srv/http/lnblog/lib/Storage/EntryRepository.php(34): LnBlog\\Storage\\EntryRepository->getEntriesRecursive()\n#3 /srv/http/lnblog/lib/Blog.php(619): LnBlog\\Storage\\EntryRepository->getLimit()\n#4 /srv/http/lnblog/lib/WebPages.php(2146): Blog->getEntries()\n#5 /srv/http/lnblog/lib/WebPages.php(1557): WebPages->getWeblog()\n#6 /srv/http/lnblog/lib/WebPages.php(79): WebPages->showblog()\n#7 /srv/http/lnblog/lib/BasePages.php(137): WebPages->defaultAction()\n#8 /srv/http/lnblog/lib/BasePages.php(66): BasePages->handleRequestRouting()\n#9 /srv/http/lnblog/pages/showblog.php(4): BasePages->routeRequest()\n#10 /srv/http/12bytes/index.php(4): include('...')\n#11 {main}\n  thrown in /srv/http/lnblog/lib/FS.php on line 332, referer: http://localhost:8000/lnblog/
```

</details>

**Comment by atomGit** [comment]
additional: i deleted the original test blog (which resulted in a blank page) and attempted to create a new one - this also resulted in several php errors and the following in the UI:

> Error creating blog. This could be a problem with the file permissions on your server. Please refer to the [documentation](http://www.skepticats.com/LnBlog/documentation/) for more information.

(the 'documentation' link is 404 btw)

so i scrapped the whole thing, re-extracted the zip, restarted httpd and now i cannot create a blog at all without errors which doesn't make any sense to me since it worked the first time

**Comment by pageer** [comment]
Hi @atomGit!

Well, I knew the documentation was out of date.  Apparently the links to it are as well.  (The correct link is https://lnblog.skepticats.com/documentation/, for what it's worth.)

From the logs you posted, this is almost certainly some kind of permissions problem.  The trace indicates that an `opendir()` call failed, which would only happen if the directory didn't exist or couldn't be read.  The permission fixing tool is extremely limited and can't do much about file ownership issues, so I'm not surprised it didn't work.

Basically, the web server process needs to have full read/write permissions to wherever you want it to write files.  You just need to know what user Apache is running as and where you're writing files (which you should be able to see/set in LnBlog).  Make sure that user has rwx permissions on that location and you should be good.

I don't know anything about Manjaro, but I just tried a fresh setup on my Ubuntu box.  My process was:
1. Create a `/var/www/html/lnblog` directory and extract the LnBlog-2.3.2.zip file there.
2. Set the entire document root (which is `/var/www/html` on my box) and everything under it to be owned by the process as which Apache is running.  On Ubuntu, that's `www-data`, so I ran `sudo chown -R www-data.www-data /var/www/html`.  
3. Verify that permissions on both `/var/www/html` and `/var/www/html/lnblog` are set to 755 (rwxr-xr-x).  (LnBlog needs to write `pathconfig.php` in its installation dir and it generally assumes that it will create blogs and the userdata directory in the server's document root.)
4. Go to `http:/myhost/lnblog` in a browser and go through the setup process.
5. After initial setup and creating an admin user, create a blog.  (See important note below.)
6. Go to the blog and create a post.

 **IMPORTANT NOTE**: When creating the blog, look at the blog URL box and _make sure it ends with a slash_, like `http://myhost/myblog/`.  If it doesn't, various links will break, like the new post link.  It does not appear to be adding that by default (mine was `http://myhost/myblog`), which is a bug, but it can be worked around by just adding it manually.  If you fail to do this when creating the blog, you can change the URL by going to `http://myhost/myblog/?action=blogpaths` (this is the "edit blog paths" link on the blog settings page).

As far as cleanup, in addition to the LnBlog and individual blog directories, there's also the `userdata` directory.  That's usually created in the same directory as the LnBlog install and contains various global settings and user information.

I hope that helps.  If you continue to have problems, please let me know what errors you're getting so I can try and track them down.  I'll also fix that bug with the default blog URL when I get a chance.

Thanks for the feedback!

**Comment by atomGit** [comment]
i'm still have problems ... what i did:

on manjaro, which i affectionately call 'arch for dummies', apache user:group is 'http:http' and the server root is /srv/http/

i'm using the master branch (downloading the master zip, not the release - is that right?) and since i'm testing a pile of CMSs i put lnblog in /srv/http/lnblog

i set user:group...
`$ sudo chown http:http -R /srv/http/`

and permissions...
`$ sudo find /srv/http/ -type d -exec chmod 755 {} +`
`$ sudo find /srv/http/ -type f -exec chmod 644 {} +`

`$ systemctl status httpd` reports all is fine

when i open `http://localhost:8000/lnblog/` it's blank and the error is:
```
[php:warn] [pid 10260] [client 127.0.0.1:34074] PHP Warning:  require_once(/srv/http/lnblog/vendor/autoload.php): Failed to open stream: No such file or directory in /srv/http/lnblog/blogconfig.php on line 18, referer: http://localhost:8000/

[php:error] [pid 10260] [client 127.0.0.1:34074] PHP Fatal error:  Uncaught Error: Failed opening required '/srv/http/lnblog/vendor/autoload.php' (include_path='.:') in /srv/http/lnblog/blogconfig.php:18\nStack trace:\n#0 /srv/http/lnblog/index.php(2): require_once()\n#1 {main}\n  thrown in /srv/http/lnblog/blogconfig.php on line 18, referer: http://localhost:8000/
```

i don't know where the port (127.0.0.1:34074) is coming from as that's not anywhere in the config

httpd.conf...
```
ServerName host.localhost:8000

User http
Group http

DocumentRoot "/srv/http"
<Directory "/srv/http">
    Options Indexes FollowSymLinks
    AllowOverride all
    Require all granted
</Directory>
```

**Comment by pageer** [comment]
The `[client 127.0.0.1:34074]` appears to be the client info, i.e. the port your browser is using.  Nothing to worry about.

Look at the "building from source" section of the README.md.  The actual error is because PHP isn't finding the Composer dependencies (i.e. the stuff in the `vendor` directory).  If you're just cloning from Git, there are additional steps to install the PHP and JavaScript dependencies.  But you need some dev tools to install those, which is why there's a release file. 😄 

If you don't want to do that, you can also just take the code from Git and copy it over what's in the release zip file.  The only thing the build steps do is create the `vendor` and `third-party` directories that are in the release zip.  Those are what you actually need.
